TOPDIR ?= ../..
include $(TOPDIR)/.config

$(WS2801_SUPPORT)_SRC += protocols/ws2801/ws2801.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
