TOPDIR ?= ../..
include $(TOPDIR)/.config

$(WS2801_EFFECT_SUPPORT)_SRC += \
			services/ws2801-effect/ws2801-effect.c \
			services/ws2801-effect/ws2801-effect-ecmd.c \

#########################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
