TOPDIR ?= ../..
include $(TOPDIR)/.config

$(WS2801_STORAGE_SUPPORT)_SRC += \
	services/ws2801-storage/ws2801_storage.c \
	services/ws2801-storage/ws2801_storage_ecmd.c \

#########################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
